### Get counters
GET http://localhost:3000/counters/getAllCounters

### Get counter by ID
GET http://localhost:3000/counters/1

### create counter
POST http://localhost:3000/counters/create
Content-Type: application/json

{
    "counter": 2,
    "comment": "New"
}

### Get games
GET http://localhost:3000/games/getGames

### Get game
GET http://localhost:3000/games/3

### Delete game
DELETE http://localhost:3000/games/2

### Get game
POST http://localhost:3000/games/2/addPointTeam1

### Get game
POST http://localhost:3000/games/2/addPointTeam2

### reset game
POST http://localhost:3000/games/4/reset

### create game
GET http://localhost:3000/games/createGame
Content-Type: application/json

{
    "counter": 2,
    "comment": "New"
}

### put updateInfo
PUT http://localhost:3000/games/2/updateInfo
Content-Type: application/json

{  
  "gameName": "gameNam1e"
}